cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

ecomerseapp/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.prodDetail, name='prodDetail'),
    # path('<slug:c_slug>/<slug:product_slug>/',views.prodDetail,name='prodCatdetail')
    path('<slug:c_slug>/<slug:product_slug>/', views.prodDetail, name='prodDetail'),
]

ecomersepro/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from ecomersepro.settings import STATIC_URL

urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/',include('search_app.urls')),
    path('cart/',include('cart_app.urls')),
    path('',include('ecomerseapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views


app_name='search_app'
urlpatterns= [
    path('',views.SearchResult,name='SearchResult'),
]

cart_app/models.py
from django.db import models
from ecomerseapp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecomerseapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    updated=models.DateField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('shop:prodDetail', args=[self.category.slug, self.slug])
        # return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomerseapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        request.session.create()
        cart = request.session.session_key
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()

    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price*cart_item.quantity)
            counter +=cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1 :
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete
    return redirect('cart_app:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecomerseapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from ecomerseapp.models import Category, Product


# Create your views here.

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def prodDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ecomerseapp.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    # products=None
    # query=None
    # if 'q' in request.GET:
    #     query=request.GET.get('q')
    #     products=Product.objects.filter(Q(name__contains=query) | Q(description__contains=query))
    # return render(request,'search.html',{'query':query,'products':products})
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        if query.isalnum():
            products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
    <script src="https://kit.fontawesome.com/f7d3bcaa44.js" crossorigin="anonymous"></script>


    <meta name="descriptions" content="{% block metadescription %} {% endblock %}">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">


    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block body %}
    {% endblock %}
    {% include 'footer.html' %}
<!--            <script src="{% static 'js/popper.min.js' %}"></script>-->
<!--            <script src="{% static 'js/bootstrap.min.js' %}" ></script>-->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>


</div>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the Cart page, come and have a view once more to varify
{% endblock %}

{% block title %}
 Cart - ABC Compay Pvt Ltd
{% endblock %}
{% block body %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
    <h1 class="text-center my_title">
        Your Shoping Cart Is Empty
    </h1>
        <br>
        <p class="text-center">
            please click <a href="{% url 'shop:allProdCat' %}">Here</a>to continue shoping.

        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        your items

                    </th>
                </tr>
                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td style="width: 100px; height: 100px;">
                        <a href="{% url 'shop:prodDetail' cart_item.product.category.slug cart_item.product.slug %}">
                            <img src="{{cart_item.product.image.url}}" alt="" style="width: 100%; height: 100%; object-fit: cover;" class="float-left rounded custom_image"></a>

                    </td>
                    <td class="text-lef" style="width: 250px;">
                        {{cart_item.product.name}}
                        <br>
                        SKU:{{cart_item.product.id}}
                        <br>
                        Price: $ {{cart_item.product.price}}
                        <br>
                        QTY :{{cart_item.quantity }} x $ {{cart_item}}

                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a" ><i class="fa fa-plus custom_icon" ></i></a>&nbsp;
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center">
        <table class="my_custom_tabel">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review you shopping cart item before proceeding with the order payment
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your Total Is : <strong> {{total}}</strong>
        </td>
         </tr>
        </tbody>
            </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to ABC Shop
    {% endif %}
{% endblock %}

{% block title %}
{% if category %}
        {{category.name}} - ABC Store
    {% else %}
        See Our New Collections - ABC Store
    {% endif %}
{% endblock %}

{% block body %}
{% if category %}
<div>
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
        <p>
            <a href="{% url 'shop:allProdCat' %}">Our Porduct Collectoin</a>
        </p>
    </div>
        </div>

</div>
</div>
{% endif %}

<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}

<div>


<img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products" width="1330;" >
     </div>
<br>
<div>
    <h1 class="text-center my_title">
        Our Product Collection
    </h1>
    <p class="text-justify">The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
</div>
{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="minimum-width:18rem;">

                <a href="{% url 'shop:prodDetail' c_slug=product.category.slug product_slug=product.slug %}">
                    {% if product.image %}
                <img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width: 100%; height: 400px;">
                {% else %}
                         <div class="no-image-placeholder">No Image Available</div>
                     {% endif %}
            </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm" {% if products.number == pg %} active {% endif %}>{{pg}}</a>
            {% endfor %}

        </div>
        {% endif %}



    </div>
    <br>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;ABC Tech Pvt.ltd All Rights Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"></a><img class="my_img1" src="{% static 'img/logo1.png' %}" alt="logoimage">
    </center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:allProdCat' %}">Shop</a>
      </li>
      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
          {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{ cat.name }}</a></li>
          {% endfor %}
        </ul>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-shopping">({{item_count}})</i> Cart</a>
      </li>
      {% endif %}
    </ul>
    <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
{% if category %}
        {{product.name}} - ABC Store

    {% endif %}
{% endblock %}


{% block body %}
<!--<div class="my_prod_row_class">-->
<!--    <div class="mx_auto">-->
<!--        <p>-->
<!--            <a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.name}}</a> | {{product.name}}-->
<!--        </p>-->
<!--    </div>-->
<!--</div>-->
<!--<div class="container">-->

<!-- <br>-->

<!--<div class="row">-->
<!--    <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center">-->
        <!--<div style="max-width: 100%; height: auto;">-->
            <!--<div class="card mb-3" style="height: 200px; weight: 200px;">-->
<!--            <a href="{% url 'shop:prodDetail' product.category.slug product.slug %}">-->
<!--                <img src="{{product.image.url}}" alt="{{product.name}}" style="max-width: 100%; height: auto;"></a>-->
<!--        </div>-->
<!--    </div>-->

<!--        <div class="col-12 col-sm-12 col-md-6 col-lg-6">-->
<!--            <div>-->
<!--            <h1 class="my_prod_title">{{product.name}}</h1>-->
<!--            <p>${{product.price}}</p>-->
<!--            <p class="my_title">Product Description</p>-->
<!--            <p class="text-justify text-justify my_prod_text">{{product.description}}</p>-->
<!--            {% if product.stock <= 0 %}-->
<!--            <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>-->
<!--             {% else %}-->
<!--            <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}"> Add To Cart</a>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--    </div>-->
<!--</div>-->



<div class="container">
    <div class="row">
        <div class="col-md-6">
            <!--<div class="col-12 col-sm-12 col-md-6 col-lg-6">-->
            <div class="my_prod_row_class">
                <div class="mx-auto">
                    <p>
                        <a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.name}}</a> | {{product.name}}
                    </p>
                </div>
            </div>
            <div class="text-center">
                <a href="{% url 'shop:prodDetail' product.category.slug product.slug %}">
                    <img src="{{product.image.url}}" alt="{{product.name}}" style="max-width: 100%; height: auto;">
                </a>
            </div>
        </div>
        <div class="col-md-6"><br>
            <div><br>
            <!--<div class="col-12 col-sm-12 col-md-6 col-lg-6">-->
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}"> Add To Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We Have Varify
{% endblock %}

{% block title %}
Search
{% endblock %}
{% block body %}
<div>
    <p class="text-center my_search">You Have Searched For :<b>"{{query}}"</b></p>
     {% if products %}
    <div class="container">
        <div class="row mx_auto">
            {% for product in products %}
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="container">
        <div class="row mx_auto">
            <div class="col">
                <p class="text-center my_search_text">0 Results Found</p>
            </div>
        </div>
    </div>
    {% endif %}
</div>

<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4">
            <div class="card text-center" style="minimum-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>

        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"></p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}